// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_embeddings`, `cosine_similarity`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EMBEDDING_CACHE`, `MODEL`, `TOKENIZER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `deref`, `fmt`, `initialize`, `initialize`, `initialize`

Future<void> clearCache() => RustLib.instance.api.crateApiAlignmentClearCache();

Future<void> loadModel(
        {required String onnxPath, required String tokenizerPath}) =>
    RustLib.instance.api.crateApiAlignmentLoadModel(
        onnxPath: onnxPath, tokenizerPath: tokenizerPath);

Future<List<AlignmentPair>> alignSentences(
        {required List<String> sourceSentences,
        required List<String> targetSentences,
        required int maxAlign}) =>
    RustLib.instance.api.crateApiAlignmentAlignSentences(
        sourceSentences: sourceSentences,
        targetSentences: targetSentences,
        maxAlign: maxAlign);

Future<List<AlignmentPair>> alignWordsGreedy(
        {required List<String> sourceWords,
        required List<String> targetWords,
        required double threshold}) =>
    RustLib.instance.api.crateApiAlignmentAlignWordsGreedy(
        sourceWords: sourceWords,
        targetWords: targetWords,
        threshold: threshold);

class AlignmentPair {
  final Int32List sourceIndices;
  final Int32List targetIndices;
  final double score;

  const AlignmentPair({
    required this.sourceIndices,
    required this.targetIndices,
    required this.score,
  });

  @override
  int get hashCode =>
      sourceIndices.hashCode ^ targetIndices.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlignmentPair &&
          runtimeType == other.runtimeType &&
          sourceIndices == other.sourceIndices &&
          targetIndices == other.targetIndices &&
          score == other.score;
}
